name: jamqpwa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  shimmer: ^1.1.1
  animated_button: ^0.1.2
  group_radio_button: ^1.0.1
  gradient_widgets: ^0.5.1
  flutter_verification_code: ^0.2.1
  rflutter_alert: ^1.0.3
  clipboard: ^0.1.2+8
  file_picker_web: ^1.0.1+1
  image_picker_web: ^1.0.9
  dio_retry: ^0.1.9-beta
  lottie_flutter: ^0.2.0
  persian_datepicker: ^1.3.1
  jalali_date: ^0.1.5
  responsive_framework: ^0.0.9
  show_up_animation: ^1.0.4
  cached_network_image: ^2.3.2+1
  confetti: ^0.5.4+1
  fbutton: ^2.0.1
  flutter_material_pickers: ^1.8.0
  shared_preferences: ^0.5.7+1
  fluttertoast: ^4.0.1
  socket_io_client: ^0.9.10
  flutter_radio_button_group: ^0.0.2+3
  dio: 3.0.9
  material_segmented_control: ^2.1.0+1
  custom_radio_grouped_button: ^1.0.6+1
  circular_countdown_timer: ^0.0.7
  aho_corasick: ^1.1.0
  rive: ^0.6.2
  url_launcher: ^5.7.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/navmenu.png
    - assets/images/profile.png
    - assets/images/homeico.png
    - assets/images/profileic.png
    - assets/images/drawer.png
    - assets/images/friendico.png
    - assets/images/groupgame.png
    - assets/images/settingico.png
    - assets/images/shopico.png
    - assets/images/Surveyico.png
    - assets/images/talentico.png
    - assets/images/teachico.png
    - assets/images/score.png
    - assets/images/rect.png
    - assets/images/scoreico.png
    - assets/images/cup.png
    - assets/images/setting.png
    - assets/images/life.png
    - assets/images/coin.png
    - assets/images/cupico.png
    - assets/images/tournementico.png
    - assets/images/newsico.png
    - assets/images/rankico.png
    - assets/images/anuncment.png
    - assets/images/sendticketback.png
    - assets/images/babr.jpg
    - assets/images/cam.png
    - assets/images/email.png
    - assets/images/phone.png
    - assets/images/name.png
    - assets/images/socialcode.png
    - assets/images/inputnumberback.jpg
    - assets/images/number.png
    - assets/images/identifiercode.png
    - assets/images/lock.png
    - assets/images/retry.png
    - assets/images/splashback.jpg
    - assets/images/applogo.png
    - assets/images/backico.png
    - assets/images/aboutuswhiteback.png
    - assets/images/emailblue.png
    - assets/images/phoneblue.png
    - assets/images/plussign.png
    - assets/images/pepole.png
    - assets/images/sendico.png
    - assets/images/aboutusport.jpg
    - assets/images/aboutusland.jpg
    - assets/images/ticketdetail.png
    - assets/images/ticketdetails.png
    - assets/images/ticketdetailspicland.png
    - assets/images/ticketdetailsland.png
    - assets/images/sendticketbackland.png
    - assets/images/sendticketback.png
    - assets/images/transactiondetailsland.png
    - assets/images/transactiondetailsport.png
    - assets/images/Transactiondetailpic.png
    - assets/images/profileport.png
    - assets/images/profileland.png
    - assets/images/profback.png
    - assets/images/emailico.png
    - assets/images/dateico.png
    - assets/images/banknumberico.png
    - assets/images/phoneico.png
    - assets/images/genderico.png
    - assets/images/picc.json
    - assets/images/questionbkg.jpg
    - assets/images/questionsbackport.png
    - assets/images/questiontopprot.png
    - assets/images/categoryitemsback.png
    - assets/images/drawerbkg.jpg
    - assets/images/dhome.png
    - assets/images/daboutus.png
    - assets/images/dinvitecode.png
    - assets/images/dscores.png
    - assets/images/dsendticket.png
    - assets/images/dtransactions.png
    - assets/images/dwatchad.png
    - assets/images/nextqs.png
    - assets/images/nextqsreaport.png
    - assets/images/nextqsshare.png
    - assets/images/mainbackland.jpg
    - assets/images/mainbackport.jpg
    - assets/images/liveico.png
    - assets/images/rewardico.png
    - assets/images/selectopland.jpg
    - assets/images/selectopport.jpg
    - assets/images/searchico.png
    - assets/images/downmenuland.png
    - assets/images/question.png
    - assets/images/onevone.png
    - assets/images/right.png
    - assets/images/wrong.png
    - assets/images/rowbkg.png
    - assets/images/rowtitle.png
    - assets/anims/qssearch.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/IRANSans.ttf

    - family: Lale
      fonts:
        - asset: assets/fonts/Lalezar.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
