name: jamqpwa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  shimmer: ^1.1.1
  animated_button: ^0.1.2
  gradient_widgets: ^0.5.1
  flutter_verification_code: ^0.2.1
  file_access: ^1.0.3
  rflutter_alert: ^1.0.3
  file_picker_web: ^2.0.0
  image_picker_web: ^1.0.6
  dio_retry: ^0.1.9-beta
  audioplayers: ^0.15.1
  shared_preferences: ^0.5.7+1
  fluttertoast: ^4.0.1
  socket_io_client: ^0.9.10
  dio: 3.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/back.png
    - assets/images/navmenu.png
    - assets/images/profile.png
    - assets/images/homeico.png
    - assets/images/profileic.png
    - assets/images/drawer.png
    - assets/images/friendico.png
    - assets/images/groupgame.png
    - assets/images/settingico.png
    - assets/images/shopico.png
    - assets/images/Surveyico.png
    - assets/images/talentico.png
    - assets/images/teachico.png
    - assets/images/score.png
    - assets/images/rect.png
    - assets/images/scoreico.png
    - assets/images/cup.png
    - assets/images/setting.png
    - assets/images/life.png
    - assets/images/coin.png
    - assets/images/cupico.png
    - assets/images/tournementico.png
    - assets/images/newsico.png
    - assets/images/rankico.png
    - assets/images/anuncment.png
    - assets/images/babr.jpg
    - assets/images/cam.png
    - assets/images/email.png
    - assets/images/phone.png
    - assets/images/name.png
    - assets/images/socialcode.png
    - assets/images/inputnumberback.png
    - assets/images/number.png
    - assets/images/identifiercode.png
    - assets/images/lock.png
    - assets/images/retry.png
    - assets/images/splashback.png
    - assets/images/applogo.png
    - assets/images/aboutusback.png
    - assets/images/backico.png
    - assets/images/aboutuswhiteback.png
    - assets/images/emailblue.png
    - assets/images/phoneblue.png
    - assets/images/inviteback.png
    - assets/images/pepole.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/IRANSans.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
